# Generated by Django 5.0.4 on 2024-07-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_users_usersmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
