# Generated by Django 5.0.4 on 2024-07-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulemodel',
            name='user_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
